cluster:
    name: sim_ex_stream_pert1
    time: 30
    directory: {sim_out_dir}streams/
    system: cedar
    nodes: 1
    ompnum: 2
    pernode: 24
    mem: 0
    venv: {venv_dir}
    queue: batch
    account: rpp-chime
    queue_sys: slurm


pipeline:

    logging:
        root: INFO

    tasks:

        - type: draco.core.task.SetMPILogging
          params:
              level_rank0: DEBUG
              level_all: INFO

        - type: draco.core.io.LoadProductManager
          out: manager
          params:
              product_directory: {sim_out_dir}products_pert/

        - type: draco.core.io.LoadMaps
          out: map_21cmfg
          params:
              maps:
                - files:  # Multiple maps are summed
                    - "{sim_out_dir}cora_maps/in_map_21cm.h5"
                    - "{sim_out_dir}cora_maps/in_map_fg.h5"

        - type: draco.synthesis.stream.SimulateSidereal
          requires: manager
          in: map_21cmfg
          out: sstream_21cmfg
          params:
              save: Yes
              tag: "21cm_and_fg"
              output_name: "{sim_out_dir}streams/stream_pert_{{tag}}.h5"


### Optionally, can also run pipeline below, which uses Gaussian foreground maps:

#         - type: draco.core.io.LoadMaps
#           out: map_21cmgfg
#           params:
#               maps:  # Can have multiple entries under this (use different tags)
#                 - files:  # Multiple maps are summed..
#                     - "{sim_out_dir}cora_maps/in_map_21cm.h5"
#                     - "{sim_out_dir}cora_maps/in_map_gfg.h5"

#         - type: draco.synthesis.stream.SimulateSidereal
#           requires: manager
#           in: map_21cmgfg
#           out: sstack_21cmgfg
#           params:
#               save: Yes
#               tag: "21cm_and_gfg"
#               output_name: "{sim_out_dir}streams/stream_pert_{{tag}}.h5"
              
              